# Generated by Django 6.1 on 2026-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
