# Generated by Django 6.1 on 2026-08-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('LECTURE_NOTE', 'Lecture Note'), ('PRESENTATION', 'Presentation'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('LINK', 'External Link'), ('OTHER', 'Other')], default='LECTURE_NOTE', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_materials/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='courses.courseoffering')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_materials', to='lecturers.lecturer')),
            ],
            options={
                'ordering': ['week', '-created_at'],
            },
        ),
    ]
