# Generated by Django 6.1 on 2026-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
