# Generated by Django 6.1 on 2026-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignmentsubmission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
